// /trips/mockData.ts
import { Trip } from "./types";

// Mock data
export const mockTrips: Trip[] = [
  {
    id: "trip-1",
    tripName: "Business Conference - San Francisco",
    confirmationNumber: "BCONF2024SF",
    status: "upcoming",
    type: "business",
    startDate: "2024-11-15T00:00:00Z",
    endDate: "2024-11-18T00:00:00Z",
    destination: { city: "San Francisco", country: "USA", airport: "SFO" },
    origin: { city: "New York", country: "USA", airport: "JFK" },
    bookingSource: "manual",
    flights: [
      {
        id: "flight-1",
        airline: "United Airlines",
        flightNumber: "UA 123",
        departure: {
          airport: "JFK",
          city: "New York",
          dateTime: "2024-11-15T08:00:00Z",
          terminal: "4",
          gate: "12A",
        },
        arrival: {
          airport: "SFO",
          city: "San Francisco",
          dateTime: "2024-11-15T14:30:00Z",
          terminal: "3",
          gate: "45B",
        },
        duration: "6h 30m",
        aircraft: "Boeing 777",
        seatNumber: "12A",
        cabinClass: "business",
        status: "scheduled",
        confirmationNumber: "UA123ABC",
        eTicketNumber: "0162345678901",
        baggage: {
          checked: 2,
          carry: 1,
          weight: "23kg",
        },
      },
    ],
    hotels: [
      {
        id: "hotel-1",
        hotelName: "Marriott Marquis",
        chain: "Marriott",
        address: {
          street: "780 Mission St",
          city: "San Francisco",
          state: "CA",
          country: "USA",
          postalCode: "94103",
        },
        checkIn: "2024-11-15T15:00:00Z",
        checkOut: "2024-11-18T11:00:00Z",
        nights: 3,
        roomType: "Deluxe King",
        bedType: "King",
        confirmationNumber: "MARR123456",
        ratePerNight: 289,
        totalCost: 867,
        currency: "USD",
        amenities: ["WiFi", "Gym", "Pool", "Room Service"],
        status: "confirmed",
        loyaltyNumber: "MB987654321",
      },
    ],
    carRentals: [],
    activities: [
      {
        id: "activity-1",
        name: "Tech Summit 2024",
        type: "event",
        dateTime: "2024-11-16T09:00:00Z",
        duration: "8h",
        location: {
          name: "Moscone Center",
          address: "747 Howard St",
          city: "San Francisco",
        },
        confirmationNumber: "TECH2024",
        status: "confirmed",
      },
    ],
    travelers: [
      {
        id: "traveler-1",
        profileId: "profile-1",
        name: "John Smith",
        email: "john.smith@company.com",
        isPrimary: true,
      },
    ],
    totalCost: 2450,
    currency: "USD",
    paymentStatus: "paid",
    tags: ["business", "conference", "tech"],
  },
  {
    id: "trip-2",
    tripName: "Family Vacation - Miami",
    confirmationNumber: "VAC2024MIA",
    status: "upcoming",
    type: "leisure",
    startDate: "2024-12-20T00:00:00Z",
    endDate: "2024-12-27T00:00:00Z",
    destination: { city: "Miami", country: "USA", airport: "MIA" },
    origin: { city: "New York", country: "USA", airport: "JFK" },
    bookingSource: "manual",
    flights: [
      {
        id: "flight-2",
        airline: "American Airlines",
        flightNumber: "AA 456",
        departure: {
          airport: "JFK",
          city: "New York",
          dateTime: "2024-12-20T10:00:00Z",
          terminal: "8",
        },
        arrival: {
          airport: "MIA",
          city: "Miami",
          dateTime: "2024-12-20T13:30:00Z",
          terminal: "S",
        },
        duration: "3h 30m",
        seatNumber: "15F",
        cabinClass: "economy",
        status: "scheduled",
        confirmationNumber: "AA456XYZ",
        baggage: {
          checked: 2,
          carry: 2,
          weight: "23kg",
        },
      },
    ],
    hotels: [
      {
        id: "hotel-2",
        hotelName: "Ocean View Resort",
        address: {
          street: "123 Ocean Drive",
          city: "Miami Beach",
          state: "FL",
          country: "USA",
          postalCode: "33139",
        },
        checkIn: "2024-12-20T15:00:00Z",
        checkOut: "2024-12-27T11:00:00Z",
        nights: 7,
        roomType: "Ocean View Suite",
        bedType: "Queen",
        confirmationNumber: "OVR789012",
        ratePerNight: 350,
        totalCost: 2450,
        currency: "USD",
        amenities: ["Beach Access", "Pool", "Spa", "Restaurant"],
        status: "confirmed",
      },
    ],
    carRentals: [
      {
        id: "car-1",
        company: "Hertz",
        vehicleType: "SUV",
        vehicleClass: "suv",
        pickupLocation: {
          address: "Miami International Airport",
          city: "Miami",
          dateTime: "2024-12-20T14:00:00Z",
        },
        dropoffLocation: {
          address: "Miami International Airport",
          city: "Miami",
          dateTime: "2024-12-27T10:00:00Z",
        },
        confirmationNumber: "HERTZ123",
        totalCost: 560,
        currency: "USD",
        insurance: ["Basic Coverage"],
        status: "confirmed",
      },
    ],
    activities: [],
    travelers: [
      {
        id: "traveler-2",
        profileId: "profile-1",
        name: "John Smith",
        email: "john.smith@gmail.com",
        isPrimary: true,
      },
    ],
    totalCost: 3850,
    currency: "USD",
    paymentStatus: "paid",
    tags: ["family", "vacation", "beach"],
  },
  {
    id: "trip-3",
    tripName: "NYC Business Meeting",
    confirmationNumber: "BIZ2024NYC",
    status: "completed",
    type: "business",
    startDate: "2024-09-10T00:00:00Z",
    endDate: "2024-09-12T00:00:00Z",
    destination: { city: "New York", country: "USA", airport: "JFK" },
    bookingSource: "agency",
    flights: [],
    hotels: [
      {
        id: "hotel-3",
        hotelName: "Hilton Manhattan",
        chain: "Hilton",
        address: {
          street: "1335 Avenue of the Americas",
          city: "New York",
          state: "NY",
          country: "USA",
          postalCode: "10019",
        },
        checkIn: "2024-09-10T15:00:00Z",
        checkOut: "2024-09-12T11:00:00Z",
        nights: 2,
        roomType: "Business Suite",
        confirmationNumber: "HILT456789",
        ratePerNight: 299,
        totalCost: 598,
        currency: "USD",
        status: "confirmed",
      },
    ],
    carRentals: [],
    activities: [],
    travelers: [
      {
        id: "traveler-3",
        profileId: "profile-1",
        name: "John Smith",
        email: "john.smith@company.com",
        isPrimary: true,
      },
    ],
    totalCost: 598,
    currency: "USD",
    paymentStatus: "paid",
    tags: ["business", "meeting"],
  },
];
